import api from '@/api/axiosInstance'

// ─── Mock helpers ─────────────────────────────────────────────────────────────
const MOCK_DELAY_MS = 1600

/**
 * Produce a realistic structured patient guide string from a free-text prompt.
 * Used as the mock response until the real AI endpoint is live.
 */
function buildMockPatientGuide(prompt) {
  const trigger = prompt.toLowerCase()

  const symptomsText = prompt || 'As described by the patient'

  const diagnosis =
    trigger.includes('fever') && trigger.includes('cough')
      ? 'Viral upper respiratory tract infection (URTI) with pyrexia'
      : trigger.includes('fever')
        ? 'Pyrexia of unknown origin – likely viral aetiology'
        : trigger.includes('headache')
          ? 'Tension-type headache'
          : trigger.includes('diabetes')
            ? 'Type 2 Diabetes Mellitus – routine review'
            : 'Clinical assessment based on presenting symptoms'

  const medicines =
    trigger.includes('fever') || trigger.includes('pain')
      ? '- Paracetamol 500 mg\n- Ibuprofen 400 mg *(if not contraindicated)*\n- Oral Rehydration Salts (ORS)'
      : trigger.includes('cough')
        ? '- Dextromethorphan HBr 15 mg/5 ml syrup\n- Saline nasal rinse'
        : trigger.includes('diabetes')
          ? '- Metformin 500 mg\n- Glipizide 5 mg'
          : '- Medication to be determined after clinical review'

  const dosage =
    trigger.includes('fever') || trigger.includes('pain')
      ? '- **Paracetamol:** 1–2 tablets every 4–6 hours, max 8 tablets/day\n- **Ibuprofen:** 1 tablet every 8 hours with food\n- **ORS:** 200 ml after every loose stool'
      : trigger.includes('cough')
        ? '- **Syrup:** 10 ml every 6–8 hours\n- **Saline rinse:** 2–3× daily'
        : trigger.includes('diabetes')
          ? '- **Metformin:** 500 mg twice daily with meals\n- **Glipizide:** 5 mg once daily before breakfast'
          : '- As per clinical judgement — confirm with patient weight and renal profile'

  return `# CareConnect AI Patient Guide

---

## 🩺 Presenting Symptoms

${symptomsText}

## 🔍 Diagnosis

**${diagnosis}**

## 💊 Recommended Medicines

${medicines}

## 📋 Dosage Instructions

${dosage}

## 📝 Clinical Notes

> Rest advised. Stay well-hydrated. Follow up in **3–5 days** if symptoms persist or worsen. Avoid self-medication beyond the prescribed course.

---

*This patient guide was generated by CareConnect AI. Please review carefully before use.*`
}

// ─── Session cache ─────────────────────────────────────────────────────────────
/** @type {Map<string, string>} */
const sessionCache = new Map()

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate an AI patient guide for the given prompt.
 *
 * Tries the real endpoint first. Falls back to the mock when the server
 * returns a 404 / 501 (endpoint not yet implemented) or when we're
 * running against a mock-only environment.
 *
 * @param {string} prompt  Free-text description of the patient's symptoms.
 * @returns {Promise<string>}  Raw patient guide text (newline-separated sections).
 */
export async function generateAIPatientGuide(prompt) {
  const cacheKey = prompt.trim()

  if (sessionCache.has(cacheKey)) {
    // Simulate a tiny network round-trip for cached results
    await new Promise((r) => setTimeout(r, 200))
    return sessionCache.get(cacheKey)
  }

  let guideText

  try {
    const { data } = await api.post('/api/ai/prescription', { prompt })
    guideText = data?.data?.prescription ?? data?.prescription
    if (!guideText) throw new Error('Empty response from AI endpoint')
  } catch (err) {
    // Only fall back to mock if the endpoint doesn't exist yet (not for auth errors etc.)
    const status = err?.response?.status
    const isMissing = status === 404 || status === 501 || status === 502 || status === 503
    const isNetworkError = !status  // axios network error (no response)

    if (isMissing || isNetworkError) {
      // Use mock
      await new Promise((r) => setTimeout(r, MOCK_DELAY_MS))
      guideText = buildMockPatientGuide(prompt)
    } else {
      throw err
    }
  }

  sessionCache.set(cacheKey, guideText)
  return guideText
}
