name: Deploy to EC2

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            echo "Moving to project directory ........"
            cd /home/ubuntu/server/careConnect-frontend

            echo "Pulling latest code ......"
            git pull origin development

            echo "Installing dependencies ......"
            npm install

            echo "Building project ......"
            npm run build

            echo "Restarting frontend with PM2 ......"
            pm2 delete careconnect-frontend || true
            pm2 serve dist 3000 --name careconnect-frontend --spa

            echo "Saving PM2 process list ......"
            pm2 save

            echo "Deployment completed ........"
